import './styles/admin-global.scss';

import NavBar from '../components/NavBar/NavBar';
import { UserBar } from '../components/UserBar/UserBar';

export const metadata = {
  title: 'Welcome to admin-panel',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pl" className="h-100">
      <body className="d-flex h-100">
        <NavBar />
        <main className="d-flex w-100 h-100 flex-column">
          <UserBar />
          {children}
        </main>
      </body>
    </html>
  );
}
