import picture from './pictures/picture.png';

export const products = [
  {
    id: 1,
    picture: picture,
    stars: 2,
    rewievs: 3,
    name: 'Ethiopia Emerald',
    price: 150,
    currentPrice: 90,
    status: '-20%',
    availiblity: true,
  },
  {
    id: 2,
    picture: picture,
    stars: 5,
    rewievs: 10,
    name: 'Ethiopia Tradition',
    price: 90,
    status: 'statusNew',
    availiblity: false,
  },
  {
    id: 3,
    picture: picture,
    stars: 0,
    rewievs: 0,
    name: 'Ethiopia Emerald',
    price: 120,
    currentPrice: 102,
    status: '-15%',
    availiblity: true,
  },
  {
    id: 4,
    picture: picture,
    stars: 2,
    rewievs: 1,
    name: 'Ethiopia Sunrise',
    price: 80,
    currentPrice: 72,
    status: '-10%',
    availiblity: false,
  },
  {
    id: 5,
    picture: picture,
    stars: 2,
    rewievs: 5,
    name: 'Ethiopia Aroma',
    price: 150,
    availiblity: true,
  },
  {
    id: 6,
    picture: picture,
    stars: 5,
    rewievs: 6,
    name: 'Ethiopia Adventure',
    price: 160,
    currentPrice: 128,
    status: '-20%',
    availiblity: false,
  },

  // {
  //   id: 7,
  //   picture: picture,
  //   stars: 2,
  //   rewievs: 3,
  //   name: 'Ethiopia Emerald',
  //   price: 150,
  //   currentPrice: 90,
  //   status: '-20%',
  // },
  // {
  //   id: 8,
  //   picture: picture,
  //   stars: 5,
  //   rewievs: 10,
  //   name: 'Ethiopia Tradition',
  //   price: 90,
  //   status: 'statusNew',
  // },
  // {
  //   id: 9,
  //   picture: picture,
  //   stars: 2,
  //   rewievs: 3,
  //   name: 'Ethiopia Emerald',
  //   price: 150,
  //   currentPrice: 90,
  //   status: '-20%',
  // },
  // {
  //   id: 10,
  //   picture: picture,
  //   stars: 5,
  //   rewievs: 10,
  //   name: 'Ethiopia Tradition',
  //   price: 90,
  //   status: 'statusNew',
  // },
  // {
  //   id: 11,
  //   picture: picture,
  //   stars: 2,
  //   rewievs: 3,
  //   name: 'Ethiopia Emerald',
  //   price: 150,
  //   currentPrice: 90,
  //   status: '-20%',
  // },
  // {
  //   id: 12,
  //   picture: picture,
  //   stars: 5,
  //   rewievs: 10,
  //   name: 'Ethiopia Tradition',
  //   price: 90,
  //   status: 'statusNew',
  // },
  // {
  //   id: 13,
  //   picture: picture,
  //   stars: 2,
  //   rewievs: 3,
  //   name: 'Ethiopia Emerald',
  //   price: 150,
  //   currentPrice: 90,
  //   status: '-20%',
  // },
  // {
  //   id: 14,
  //   picture: picture,
  //   stars: 5,
  //   rewievs: 10,
  //   name: 'Ethiopia Tradition',
  //   price: 90,
  //   status: 'statusNew',
  // },
  // {
  //   id: 15,
  //   picture: picture,
  //   stars: 2,
  //   rewievs: 3,
  //   name: 'Ethiopia Emerald',
  //   price: 150,
  //   currentPrice: 90,
  //   status: '-20%',
  // },
  // {
  //   id: 16,
  //   picture: picture,
  //   stars: 5,
  //   rewievs: 10,
  //   name: 'Ethiopia Tradition',
  //   price: 90,
  //   status: 'statusNew',
  // },
];
