import style from './page.module.scss';
import { Lato } from 'next/font/google';
import { Logo } from '../../../public/svg/Logo';

export const metadata = {
  title: 'Log in to admin-panel',
  description: 'Generated by create-nx-workspace',
};

const lato = Lato({
  display: 'swap',
  weight: ['400', '700'],
  subsets: ['latin'],
  preload: true,
});

export default function AuthPageLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className={`${lato.className} ${style.container}`}>
      <header className={style.bgContainer}></header>
      <section>
        <Logo className={style.logo} />
        {children}
      </section>
    </div>
  );
}
