import './styles/shop-global.scss';
import NavBar from './components/NavBar/NavBar';
import { Footer } from './components/Footer/Footer';
import { InfoBanner } from './components/InfoBanner/InfoBanner';
import { Providers } from './contexts/Providers';

export const metadata = {
  title: 'Welcome to shop',
  description: 'Generated by create-nx-workspace',
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body>
        <Providers>
          <NavBar />
          <main>
            <InfoBanner />
            {children}
          </main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
};
export default RootLayout;
