import './styles/shop-global.scss';

import NavBar from './components/NavBar/NavBar';
import { Footer } from './components/Footer/Footer';
import { InfoBanner } from './components/InfoBanner/InfoBanner';

export const metadata = {
  title: 'Welcome to shop',
  description: 'Generated by create-nx-workspace',
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body>
        <NavBar />
        <main>
          <InfoBanner />

          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
};
export default RootLayout;
