import './styles/shop-global.scss';

import { Footer } from './components/Footer/Footer';
import { InfoBanner } from './components/InfoBanner/InfoBanner';
import NavBar from './components/NavBar/NavBar';
import { Providers } from './contexts/Providers';
import { Quicksand } from 'next/font/google';

export const metadata = {
  title: 'Welcome to shop',
  description: 'Generated by create-nx-workspace',
};

const quicksand = Quicksand({
  display: 'swap',
  subsets: ['latin'],
  preload: true,
});

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body className={quicksand.className}>
        <Providers>
          <NavBar />
          <main>
            <InfoBanner />
            {children}
          </main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
};
export default RootLayout;
