import '../styles/admin-global.scss';
import NavBar from '../../components/NavBar/NavBar';

export const metadata = {
  title: 'Welcome to admin-panel',
  description: 'Generated by create-nx-workspace',
};

export default function PagesLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <NavBar />
      <main>{children}</main>
    </>
  );
}
