import picture from './pictures/picture.png';

export const products = [
  {
    picture: picture,
    stars: 2,
    rewievs: 3,
    name: 'Ethiopia Emerald',
    price: 150,
    currentPrice: 90,
    status: '-20%',
  },
  {
    picture: picture,
    stars: 5,
    rewievs: 10,
    name: 'Ethiopia Tradition',
    price: 90,
    status: 'statusNew',
  },
  {
    picture: picture,
    stars: 0,
    rewievs: 0,
    name: 'Ethiopia Emerald',
    price: 120,
    currentPrice: 102,
    status: '-15%',
  },
  {
    picture: picture,
    stars: 2,
    rewievs: 1,
    name: 'Ethiopia Sunrise',
    price: 80,
    currentPrice: 72,
    status: '-10%',
  },
  {
    picture: picture,
    stars: 2,
    rewievs: 5,
    name: 'Ethiopia Aroma',
    price: 150,
  },
  {
    picture: picture,
    stars: 5,
    rewievs: 6,
    name: 'Ethiopia Adventure',
    price: 160,
    currentPrice: 128,
    status: '-20%',
  },
];
